### ISSUE TITLE
Ween temperature model does not display infos

### ISSUE THREAD

**Issue by chris-le-chti** [joggee-fr/domoticz-ween-thermostat#1]
version in wip branch, I can see but there is not temp / humidity visible
![image](https://user-images.githubusercontent.com/85738219/121873067-45d4bd80-cd06-11eb-906a-dec1926914e3.png)

no data but we have datas in log 
![image](https://user-images.githubusercontent.com/85738219/121873164-61d85f00-cd06-11eb-9a08-b6789d65a230.png)

**Comment by chris-le-chti** [comment]
![image](https://user-images.githubusercontent.com/85738219/121873263-7ddc0080-cd06-11eb-9fc3-1202c5c57180.png)

**Comment by joggee-fr** [comment]
@chris-le-chti , can you make a new test using commit 43920923771496e1eac90dd626ecf3bec68be251 (HEAD) on the `wip` branch. I think you have to remove `__pycache__` in the plugin folder and restart Domoticz after update.

I have just added a "Humidity status" to allow Domoticz to display the values.

For information: https://www.domoticz.com/wiki/Developing_a_Python_plugin

For the moment, the status is always "Comfort". We may find some threshold values to define the following states:
_Humidity status: 0 - Normal, 1 - Comfort, 2 - Dry, 3 - Wet_
The choice may also be linked to current temperature.

**Comment by joggee-fr** [comment]
Fixed.
